//CHECK CONSTATNTS
const CHECKSTATUS_OPEN = 1;
const CHECKSTATUS_CLOSED = 2;

//MENUTYPE CONSTANTS
const MENUTYPE_CHX = 1;
const MENUTYPE_CHILI = 2;
const MENUTYPE_DRINKS = 3;

//PAYMENTSTATUS CONSTANTS
const PAYMENTSTATUS_OPEN = 1;
const PAYMENTSTATUS_PAID = 2;
const PAYMENTSTATUS_COMP = 3;
const PAYMENTSTATUS_VOID = 4;

//PAYMENTTYPE CONSTANTS
const PAYMENTTYPE_CASH = 1;
const PAYMENTTYPE_CARD = 2;
const PAYMENTTYPE_CHECK = 3;
const PAYMENTTYPE_GIFTCARD = 4;

//ROLELU CONSTANTS
const ROLELU_SERVER = 1;
const ROLELU_COOK = 2;
const ROLELU_BARTENDER = 3;
const ROLELU_MANAGER = 4;

//TICKETSTATUS CONSTANTS
const TICKETSTATUS_OPEN = 1;
const TICKETSTATUS_SENT = 2;
const TICKETSTATUS_WORKING = 3;
const TICKETSTATUS_CLOSED = 4;

//TICKETTYPE
const TICKETTYPE_KITCHEN = 1;
const TICKETTYPE_BAR = 2;

//STORE
const StoreID = 1;

//ISACTIVE CONSTANTS
const ISACTIVE_ACTIVE = 1;
const ISACTIVE_INACTIVE = 0;

//